version: '3.9'


services:

  chat-db:
    container_name: chat-db
    image: postgres:13.7-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env

  chat-app:
    container_name: chat-app
    build:
      context: .
      network: host
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/usr/src/backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - chat-db

